# Đảm bảo Spring Boot trả dữ liệu với UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# Thông tin kết nối cơ sở dữ liệu SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LTDD_TheLa;encrypt=false
spring.datasource.username=test
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate và JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

# Mail Configuration (nếu cần thiết)
# Để mật khẩu trong biến môi trường để tăng cường bảo mật
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=craftcornerfurniture@gmail.com
spring.mail.password=mhzh cegr tcgb onyh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


server.port=9000